Title: URL not found
Date: 05/2023

Question:

I am getting:

huggingface_hub.utils._errors.HfHubHTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/mosaicml/mpt-7b-chat 
This is the snippet of code I am running:

import transformers
model = transformers.AutoModelForCausalLM.from_pretrained(
  'mosaicml/mpt-7b-chat',
  trust_remote_code=True
) 
Yesterday it worked, this morning it doesn't.

Answer:

I think this is a transient HF Hub error, their API occasionally goes down. Could you try it once more?